### ISSUE TITLE
🔒 Enable securityContext Configuration in OCS Inventory Helm Chart

### ISSUE THREAD

**Issue by siddjellali** [OCSInventory-NG/helm-charts#14]
Currently, the pods deployed via the OCS Inventory Helm chart do not enforce security best practices such as running as a non-root user. To improve security and compliance, we should allow setting a securityContext in the Helm chart values and apply it to each pod by default.

## Proposed Changes:
Add a securityContext section to the Helm chart values.yaml to allow customization.
Ensure the following default settings are applied to each pod:
```
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ "ALL" ]
```

Modify the deployment templates (deployment.yaml, statefulset.yaml, etc.) to include this securityContext configuration when specified in values.yaml.

Ensure backward compatibility by making this feature configurable.

## Benefits:
✅ Enforces better security practices by running the application as a non-root user.
✅ Reduces the risk of privilege escalation attacks.
✅ Aligns with Kubernetes security best practices.

## Tasks:
 
- Update values.yaml to support securityContext.
- Modify the Helm templates to apply the security context.
- Test deployment with the new security settings.
- Update documentation to reflect these changes.
